### ISSUE TITLE
HP not updating on Combat screen

### ISSUE THREAD

**Issue by Deadlander** [KyleADOlson/CombatManager#2]
When editing HP for a party member in the Monster Editor, it does not update on the combat screen.

**Comment by KyleADOlson** [comment]
I've made a change which will cause the MaxHP (but not the current HP) to change whenever the editor changes in the Monster.  (For historical reasons, every "Character" has a "Monster", and each have a separate Maximum HP which mistakenly were only linked in one direction).

When I finally get updates pushed out (hopefully soon), this will be there.

**Comment by Deadlander** [comment]
Awesome, I am looking forward to any updates and additions that are forthcoming!
